apiVersion: v1
kind: Service
metadata:
  name: ciam-demo-backend-service
spec:
  type: LoadBalancer
  selector:
    app: ciam-demo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080